// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCore.DataAccess.Entities;

public partial class Order
{
    public int Orderid { get; set; }

    public string Ordername { get; set; }

    public string Orderdesc { get; set; }
}