// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCore.DataAccess.Entities;

/// <summary>
/// Product descriptions in several languages.
/// </summary>
public partial class ProductDescription1
{
    /// <summary>
    /// Primary key for ProductDescription1 records.
    /// </summary>
    public int ProductDescription1Id { get; set; }

    /// <summary>
    /// Description of the product.
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }
}