// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EFCore.DataAccess.Config;
using EFCore.DataAccess.Entities;
using Microsoft.EntityFrameworkCore;


namespace EFCore.DataAccess.Data;

public partial class AdventureWorksLT2016Context : DbContext
{
    private readonly string _connectionString;
    
    public AdventureWorksLT2016Context(DbContextOptions<AdventureWorksLT2016Context> options)
        : base(options)
    {
    }
    public AdventureWorksLT2016Context(string connectionString)
    {
        _connectionString = connectionString;        
    }

    public virtual DbSet<Address> Addresses { get; set; }

    public virtual DbSet<BuildVersion> BuildVersions { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }

    public virtual DbSet<ErrorLog> ErrorLogs { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductCategory> ProductCategories { get; set; }

    public virtual DbSet<ProductDescription> ProductDescriptions { get; set; }

    public virtual DbSet<ProductModel> ProductModels { get; set; }

    public virtual DbSet<ProductModelProductDescription> ProductModelProductDescriptions { get; set; }

    public virtual DbSet<SalesOrderDetail> SalesOrderDetails { get; set; }

    public virtual DbSet<SalesOrderHeader> SalesOrderHeaders { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AS");
        modelBuilder.ApplyConfiguration(new AddressConfig());
        modelBuilder.ApplyConfiguration(new BuildVersionConfig());
        modelBuilder.ApplyConfiguration(new CustomerConfig());
        modelBuilder.ApplyConfiguration(new CustomerAddressConfig());
        modelBuilder.ApplyConfiguration(new ErrorLogConfig());
        modelBuilder.ApplyConfiguration(new OrderConfig());
        modelBuilder.ApplyConfiguration(new ProductConfig());
        modelBuilder.ApplyConfiguration(new ProductCategoryConfig());
        modelBuilder.ApplyConfiguration(new ProductDescriptionConfig());
        modelBuilder.ApplyConfiguration(new ProductModelConfig());
        modelBuilder.ApplyConfiguration(new ProductModelProductDescriptionConfig());
        modelBuilder.ApplyConfiguration(new SalesOrderDetailConfig());
        modelBuilder.ApplyConfiguration(new SalesOrderHeaderConfig());    

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    protected override void OnConfiguring(DbContextOptionsBuilder options)
    {
        options.UseSqlServer(_connectionString);    
    }
}